# Generated by Django 5.2.6 on 2025-10-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modelagem_banco',
            fields=[
                ('ID_livro', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=10)),
                ('isbn', models.DecimalField(decimal_places=0, max_digits=20)),
            ],
        ),
    ]
