# Generated by Django 5.2.6 on 2025-10-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelagem_banco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=10)),
                ('isbn', models.DecimalField(decimal_places=0, max_digits=20)),
            ],
        ),
        migrations.DeleteModel(
            name='modelagem_banco',
        ),
    ]
