# Generated by Django 5.2.6 on 2025-10-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelagem_banco', '0002_livro_delete_modelagem_banco'),
    ]

    operations = [
        migrations.CreateModel(
            name='autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('biografia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('livro', models.CharField(max_length=50)),
                ('data', models.DateField(max_length=10)),
                ('devolucao', models.DateField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('numero_identificacao', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(max_length=20),
        ),
    ]
