# Generated by Django 5.2.6 on 2025-10-01 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelagem_banco', '0003_autor_categoria_emprestimo_usuario_alter_livro_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='devolucao',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='livro_categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelagem_banco.categoria')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelagem_banco.livro')),
            ],
        ),
        migrations.CreateModel(
            name='usuario_autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelagem_banco.autor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelagem_banco.usuario')),
            ],
        ),
    ]
