# Generated by Django 5.2.8 on 2025-11-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('filme', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('altura', models.FloatField()),
            ],
        ),
    ]
