# Generated by Django 5.2.8 on 2025-11-19 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ator_dublador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('nacionalidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('ano_lancamento', models.DateField()),
                ('estudio_produtora', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='personagem_habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_sistema.habilidade')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_sistema.personagem')),
            ],
        ),
    ]
