# Generated by Django 5.2.8 on 2025-11-19 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sistema', '0002_ator_dublador_habilidade_obra_personagem_habilidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relacionamento',
            fields=[
                ('id_ralacionamento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_relacionamento', models.CharField(max_length=100)),
                ('id_personagem_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personagem_destino', to='api_sistema.personagem')),
                ('id_personagem_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personagem_origem', to='api_sistema.personagem')),
            ],
        ),
    ]
